[build]
  # This command will be run by Netlify to build your site.
  # 1. Install dependencies.
  # 2. Collect all static assets (CSS, JS, images) into the 'staticfiles' directory.
  # 3. Generate the static HTML pages directly into the 'staticfiles' directory.
  command = "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py build_static_pages"
  
  # This is the directory that Netlify will deploy.
  publish = "staticfiles/"

[[redirects]]
  from = "/scan/"
  to = "/scan/index.html"
  status = 200

[[redirects]]
  from = "/listen/:slug/"
  to = "/listen/:slug/index.html"
  status = 200
